version: "3.7"

services:
  soularr:
    image: ghcr.io/mrusse/soularr:latest
    container_name: soularr
    user: "1000:1000"
    environment:
      - TZ=${TZ}
      - SCRIPT_INTERVAL=${SCRIPT_INTERVAL:-300}
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${ROOT_FOLDER_HOST}/media/downloads/complete:/downloads
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true
